backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true

    fields:
      - { label: "Titulo", name: "title", widget: "string" }

      - { label: "Contenido", name: "body", widget: "markdown" }